# Generated by Django 4.0.6 on 2022-07-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='total',
        ),
    ]
