# Generated by Django 4.0.6 on 2022-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0002_rename_price_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnames', models.CharField(max_length=20)),
                ('mechanics', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.URLField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lister', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.CharField(blank=True, max_length=50, null=True)),
                ('listingid', models.IntegerField()),
            ],
        ),
    ]
