# Generated by Django 4.0.6 on 2022-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
