# Generated by Django 4.0.6 on 2022-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0004_cart_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='descriptions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
