# Generated by Django 4.0.6 on 2022-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0005_wishlist_prices_alter_carpart_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='buyer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
