# Generated by Django 4.0.6 on 2022-07-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0006_mechanic_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='introductions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='rates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
