# Generated by Django 4.0.6 on 2022-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0008_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnames', models.CharField(max_length=20)),
                ('images', models.URLField(blank=True, null=True)),
                ('lister', models.CharField(blank=True, max_length=64, null=True)),
                ('buyer', models.CharField(blank=True, max_length=64, null=True)),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('listingid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
