# Generated by Django 4.0.6 on 2022-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0014_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='productnames',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
