# Generated by Django 4.0.6 on 2022-07-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0015_checkout_images_checkout_productnames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='listingid',
        ),
    ]
