# Generated by Django 4.0.6 on 2022-07-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0016_remove_checkout_listingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='listingid',
        ),
    ]
