# Generated by Django 4.0.6 on 2022-07-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0017_remove_transaction_listingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
