# Generated by Django 4.0.6 on 2022-07-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0019_apprating_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
