# Generated by Django 4.0.6 on 2022-07-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0021_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
