# Generated by Django 4.0.6 on 2022-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0022_alter_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
