# Generated by Django 4.0.6 on 2022-07-31 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0024_remove_notification_listingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprating',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='apprating',
            name='listingid',
        ),
        migrations.AddField(
            model_name='apprating',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apprating',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='apprating',
            name='lister',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apprating',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apprating',
            name='ratings',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
