# Generated by Django 4.0.6 on 2022-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0026_mechanicrating_userpassword_apprating_listingid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=30)),
                ('newpassword', models.CharField(max_length=30)),
                ('security1', models.CharField(max_length=30)),
                ('security2', models.CharField(max_length=30)),
                ('security3', models.CharField(max_length=30)),
            ],
        ),
    ]
