# Generated by Django 4.0.6 on 2022-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0027_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='oldpassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='newpassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
