# Generated by Django 4.0.6 on 2022-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0029_alter_mechanicrating_mechanics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicrating',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicrating',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
