# Generated by Django 4.0.6 on 2022-08-01 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0030_alter_mechanicrating_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicrating',
            name='ratings',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
