# Generated by Django 4.0.6 on 2022-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmechanic', '0033_alter_apprating_ratings_alter_mechanicrating_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicrating',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
